### ISSUE TITLE
HERMES : Erreur lors de l'utilisation de l'action "core/apply_stimulus"

### ISSUE THREAD

**Issue by Dsniss** [Ousret/hermes#25]
@Ousret 

Je souhaite créer un automate dont l'objectif est d'utiliser l'action "core/apply_stimulus" afin de changer l'état de plusieurs tickets en une seule action, et ainsi abandonner/clore plusieurs tickets ITOP à la fois.

Ma requête détecte bien plusieurs enregistrements, mais j'obtiens une erreur en sortie. 

_**Requête utilisée**_
SELECT ServiceChange WHERE last_update<DATE(DATE_SUB(NOW(),INTERVAL IF(DATE_FORMAT(NOW(),'%w')=0,6,DATE_FORMAT(NOW(),'%w')-1)+120 DAY))

**_Erreur détectée_**
2020-04-08 18:57:56.755 | ERROR    | hermes.automate:je_realise:796 - La requête core/apply_stimulus iTop REST 'SELECT ServiceChange WHERE last_update<DATE(DATE_SUB(NOW(),INTERVAL IF(DATE_FORMAT(NOW(),'%w')=0,6
,DATE_FORMAT(NOW(),'%w')-1)+120 DAY))' n'a pas aboutie correctement. Une erreur a été soulevée (code 100) : Error: Several items found (2) for query: SELECT ServiceChange WHERE request_state="SUSPENDU" AND last_update<DATE(DATE_SUB(NOW(),I
NTERVAL IF(DATE_FORMAT(NOW(),'%w')=0,6,DATE_FORMAT(NOW(),'%w')-1)+120 DAY))
2020-04-08 18:57:56.757 | WARNING  | hermes.automate:_jai_echouee:233 - Échec de l'action 'MAJ stimulus ticket ITOP - Abandon demande pré autorisée' sur '[NOTIF_DELAI_DEPASSE Alerte demandeurs']
2020-04-08 18:57:56.759 | WARNING  | hermes_ui.moteur.processus:thread:176 - L'automate '_TEST_Abandonne_Demande' vient de traiter avec au moins une erreur la source '[NOTIF_DELAI_DEPASSE Alerte demandeurs']

Ma question est donc de savoir l'action core/apply_stimulus fait une boucle pour appliquer le stimulus sur l'ensemble des enregistrements trouvés par la requête ? Et si ce n'est pas le cas comment gérer une boucle qui permet d'appliquer le stimulus sur l'ensemble des enregistrements ?

Merci @Ousret et bonne fin de journée

@Dsniss

**Comment by Ousret** [comment]
@Dsniss 

Désolé mais `core/apply_stimulus` ne peut pas prendre de requête dont le résultat retourne plus d'UN résultat. C'est une limitation connu d'iTop. Hermès n'a pas de concept de boucle en place pour le moment. Mais ça serai la solution idéale.

Je n'ai pas de solution sur étagère pour répondre à cela pour le moment.

**Comment by Dsniss** [comment]
@Ousret 
Ok je note et comprends que cette fonctionnalité n'est pas possible en l'état
Cette demande est plus une évolution de l'existant.
Tu peux clore mon ticket
Merci
@Dsniss
