### ISSUE TITLE
Python3 - Ubuntu 20.04 - dependency issue

### ISSUE THREAD

**Issue by dutch2005** [Ousret/hermes#34]
Python3 - Ubuntu 20.04 - dependency issue

Installed /root/.local/lib/python3.8/site-packages/hermes-1.0.13-py3.8.egg
Processing dependencies for hermes==1.0.13
Searching for emails<1.0,>=0.6.1
Reading https://pypi.org/simple/emails/
No local packages or working download links found for emails<1.0,>=0.6.1
error: Could not find suitable distribution for Requirement.parse('emails<1.0,>=0.6.1')
root@michael-itop:~/hermes#

Note:

The installation states "python setup.py install --user" ---> python3 setup.py install --user (else nothing would run).

Afaik python2.7 (minimal) was installed for nodejs / npm as a dependency.

Installation was done on a newly installed ubuntu 20.04 install (no upgrade from previous version).

**Comment by Ousret** [comment]
Hi,

try this instead, I forked the repository to patch it. 
```
pip3 install git+https://github.com/Ousret/python-emails.git --user
```

**Comment by dutch2005** [comment]
Executed the  command while in ~/hermes and it downloaded / installed a few dependences) (threw some errors about some dependences for hermes not there yet.)

Then re-started the installation of hermens and it was able to install it:


Using /usr/lib/python3/dist-packages
Searching for idna==2.8
Best match: idna 2.8
Adding idna 2.8 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /root/.local/bin

Using /usr/lib/python3/dist-packages
Searching for certifi==2019.11.28
Best match: certifi 2019.11.28
Adding certifi 2019.11.28 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for cryptography==2.8
Best match: cryptography 2.8
Adding cryptography 2.8 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for premailer==3.6.1
Best match: premailer 3.6.1
Adding premailer 3.6.1 to easy-install.pth file

Using /root/.local/lib/python3.8/site-packages
Searching for cssutils==1.0.2
Best match: cssutils 1.0.2
Adding cssutils 1.0.2 to easy-install.pth file
Installing csscapture script to /root/.local/bin
Installing csscombine script to /root/.local/bin
Installing cssparse script to /root/.local/bin

Using /root/.local/lib/python3.8/site-packages
Searching for Click==7.0
Best match: Click 7.0
Adding Click 7.0 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for setuptools==45.2.0
Best match: setuptools 45.2.0
Adding setuptools 45.2.0 to easy-install.pth file
Installing easy_install script to /root/.local/bin

Using /usr/lib/python3/dist-packages
Searching for cssselect==1.1.0
Best match: cssselect 1.1.0
Adding cssselect 1.1.0 to easy-install.pth file

Using /root/.local/lib/python3.8/site-packages
Searching for blinker==1.4
Best match: blinker 1.4
Adding blinker 1.4 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for cachetools==4.1.0
Best match: cachetools 4.1.0
Adding cachetools 4.1.0 to easy-install.pth file

**Using /root/.local/lib/python3.8/site-packages
Finished processing dependencies for hermes==1.0.13
root@michael-itop:~/hermes#**

**Comment by dutch2005** [comment]
Installed /root/.local/lib/python3.8/site-packages/hermes-1.0.13-py3.8.egg
Processing dependencies for hermes==1.0.13
Searching for emails<1.0,>=0.6.1
Reading https://pypi.org/simple/emails/
No local packages or working download links found for emails<1.0,>=0.6.1
error: Could not find suitable distribution for Requirement.parse('emails<1.0,>=0.6.1')
root@michael-itop:~/hermes# pip3 install git+https://github.com/Ousret/python-emails.git --user
Collecting git+https://github.com/Ousret/python-emails.git
  Cloning https://github.com/Ousret/python-emails.git to /tmp/pip-req-build-obw4qj1l
  Running command git clone -q https://github.com/Ousret/python-emails.git /tmp/pip-req-build-obw4qj1l
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from emails==0.6.1) (3.0.4)
Collecting cssutils
  Downloading cssutils-1.0.2-py3-none-any.whl (406 kB)
     |████████████████████████████████| 406 kB 2.4 MB/s
Collecting lxml
  Downloading lxml-4.5.0-cp38-cp38-manylinux1_x86_64.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 6.8 MB/s
Collecting premailer
  Downloading premailer-3.6.1-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: python-dateutil in /root/.local/lib/python3.8/site-packages/python_dateutil-2.8.1-py3.8.egg (from emails==0.6.1) (2.8.1)
Requirement already satisfied: requests in /root/.local/lib/python3.8/site-packages/requests-2.23.0-py3.8.egg (from emails==0.6.1) (2.23.0)
Collecting cachetools
  Downloading cachetools-4.1.0-py3-none-any.whl (10 kB)
Collecting cssselect
  Downloading cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->emails==0.6.1) (1.14.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->emails==0.6.1) (2019.11.28)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests->emails==0.6.1) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->emails==0.6.1) (1.25.8)
Building wheels for collected packages: emails
  Building wheel for emails (setup.py) ... done
  Created wheel for emails: filename=emails-0.6.1-py2.py3-none-any.whl size=57530 sha256=ddc7f23bdb5a2491b6e684e4d673c0a706fa73f2b3c16f0274bbd1285527dd4c
  Stored in directory: /tmp/pip-ephem-wheel-cache-iv92ku07/wheels/d5/cb/83/acadbfc92df038116466b2beb93395819ae931ae9b1bcf2798
Successfully built emails
ERROR: hermes 1.0.13 requires dateparser, which is not installed.
ERROR: hermes 1.0.13 requires email_validator>=1.1.0, which is not installed.
ERROR: hermes 1.0.13 requires Flask==1.1.*, which is not installed.
ERROR: hermes 1.0.13 requires Flask-Webpack<1.0,>=0.1, which is not installed.
ERROR: zeep 3.4.0 requires appdirs>=1.4.0, which is not installed.
ERROR: zeep 3.4.0 requires cached-property>=1.3.0, which is not installed.
ERROR: zeep 3.4.0 requires defusedxml>=0.4.1, which is not installed.
ERROR: zeep 3.4.0 requires isodate>=0.5.4, which is not installed.
ERROR: zeep 3.4.0 requires pytz, which is not installed.
ERROR: zeep 3.4.0 requires requests-toolbelt>=0.7.1, which is not installed.
Installing collected packages: cssutils, lxml, cachetools, cssselect, premailer, emails
  WARNING: The scripts csscapture, csscombine and cssparse are installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed cachetools-4.1.0 cssselect-1.1.0 cssutils-1.0.2 emails-0.6.1 lxml-4.5.0 premailer-3.6.1

The text above is the result from:

pip3 install git+https://github.com/Ousret/python-emails.git --user


Then ran: python3 setup.py install --user

To complete the setup.py
