### ISSUE TITLE
Hermes 1.0.13 - File not found - hermes_ui/static/build/manifest.json

### ISSUE THREAD

**Issue by dutch2005** [Ousret/hermes#35]
FileNotFoundError

FileNotFoundError: [Errno 2] No such file or directory: '...hermes/hermes_ui/static/build/manifest.json'

When I got to http://ip:5000/admin

**Comment by Ousret** [comment]
That because you need first to build the frontend manually.
You need to install NodeJS with npm then install Yarn as described in README.md

```
npm install yarn -g
cd ./hermes_ui
yarn install
yarn build
cd ..
```

On Ubuntu
```
sudo apt install nodejs
```

**Comment by Ousret** [comment]
Solved @dutch2005 ?
