### ISSUE TITLE
Import / export de Automate ... comportement incompris

### ISSUE THREAD

**Issue by arneluehrs** [Ousret/hermes#36]
[automates-1593082849.128282.json.txt](https://github.com/Ousret/hermes/files/4831132/automates-1593082849.128282.json.txt)

Apres creation de une serie de criteres, un detecteur et un automate j'ai exporte la configuration testee sans problemes.

Le fichier est en effet du JSON propre, un JasonLint ne trouve rien a redire.

Puis j'ai essaye un import dans une autre instance de Hermes (tournant dans des containers Docker)
Ceci ne marche pas, la dropbox affiche:

7.3 KB
automates-1592495012.966687.json
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

Un import de un fichier JSON ne contennant que    []   ne pose pas de problemes, mais array vide ne donne evidement pas de contenu a parser.

hermes_ui\assets\scripts\app_hermes.js  
Semble etre le lieu ou ca plante.

**Comment by arneluehrs** [comment]
[automates-1593082849.128282.json.txt](https://github.com/Ousret/hermes/files/4831133/automates-1593082849.128282.json.txt)

**Comment by Ousret** [comment]
Bonjour,

Merci pour votre signalement. En effet il y a un bug. Une régression introduite récemment lors de la màj d'une dépendance.

```text
hermes_1   |   File "/app/hermes_ui/app.py", line 347, in export_automates
hermes_1   |     act_r = deepcopy(automate.action_racine)
hermes_1   | AttributeError: 'dict' object has no attribute 'action_racine'
```

C'est plutôt côté backend. J'essaie de proposer un correctif asap.

**Comment by Ousret** [comment]
Commit fautif: ed718e01860497b75da275e919ed068b0ddefe2b

**Comment by Ousret** [comment]
Un correctif (1.0.14) est disponible.

**Comment by arneluehrs** [comment]
Merci Beaucoup. 
Import/export marche sans problemes apres mise a jour.
