### ISSUE TITLE
Critère de recherche clé et injection iTOP incomplète si "," dans la variable

### ISSUE THREAD

**Issue by ma-los** [Ousret/hermes#39]
Bonjour,

Tout d'abord, merci pour cet automate qui est très utile.
Je rencontre un problème lors de la mise à jour de la description d'un ticket iTOP en utilisant un critère de recherche de type clé : Lorsque cette dernière contient un texte avec une virgule, il est tronqué après celle-ci.
Un exemple :
`cle: le probleme, est la virgule`

Je n'arrive pas a construire un automate qui prend en compte cette virgule. cette virgule étant vu comme la fin du srting json (?).

Merci
Mathieu

**Comment by Ousret** [comment]
Bonjour,

Avec grand plaisir.
Je ne suis pas certain de bien comprendre votre problème.

A ma première lecture, ce que je comprends de votre situation c'est : 
- J'invoque la variable `{{ cle }}`
- La variable contient `le probleme,` au lieu de `le probleme,  est la virgule`

Pouvez-vous confirmer ce scénario ? Sinon pour m'aider à définir un diagnostique, je vous prie de bien vouloir accompagner à ce fil le contenu d'auto détection par Hermès avec votre email. cf. https://github.com/Ousret/hermes/blob/master/docs/CHAPITRE-4.md#lauto-d%C3%A9tection-la-pr%C3%A9-lecture-du-moteur-hermes

Merci bien

**Comment by ma-los** [comment]
Bonjour,

la variable a bien l'air de contenir tout le texte, cependant l'action update itop coupe a la virgule.

```
{
    "informations": [],
    "titre": "Houston we have a problem R-001106",
    "hyperliens": [
        "https://test01.local"
    ],
    "identifiants": [
        "R-001106",
    ],
    "new-request": "R-001106",
    "ticket-title": "Test Support Request",
    "description": "",
    "message": "Le probleme, c'est la virgule.",
    "category": "Test Cloud",
    "username": "Customer",
    "domain": "https://test01.local",
    "browser": "Chrome 83.0.4103.116 on Windows NT 10.0",
    "timestamp": "2020-07-14T08:42:53.026Z"
}

+-------------------------------+-----------------------+-----------+-------------+----------+--------------------------------+
|              Type             | Règle                 | Execution | Obligatoire | Réussite |             Valeur             |
+-------------------------------+-----------------------+-----------+-------------+----------+--------------------------------+
|      CleRechercheInteret      | Get Tag message       |    True   |    False    |   True   | Le probleme, c'est la virgule. |
|      CleRechercheInteret      | Get Tag Category      |    True   |    False    |   True   |           Test Cloud           |
|      CleRechercheInteret      | Get Tag Ticket ref    |    True   |    False    |   True   |            R-001106            |
| ExpressionCleRechercheInteret | Find New Ticket Notif |    True   |     True    |   True   |              True              |
+-------------------------------+-----------------------+-----------+-------------+----------+--------------------------------+
```

**Comment by Ousret** [comment]
Bonjour,

Merci pour le dump. ça ce précise. En réalisant des tests de mon côté je n'ai pas pu constater ce problème en local. _Cas simple:_ En mettant à jour la description d'un ticket iTop 2.7.

Je crois que le "texte tronqué" n'a pas lieu chez Hermès. En dernier lieu, pouvez-vous vérifier dans la section "debug" si le dump de l'action concernée contient le texte tronqué ou pas. cf. https://github.com/Ousret/hermes/blob/master/docs/CHAPITRE-7.md#debug

Merci

**Comment by ma-los** [comment]
J'ai un problème avec l'historique des exécutions, le tableau ne se charge pas : 
![image](https://user-images.githubusercontent.com/52170610/87754663-b416b480-c805-11ea-8cac-c823ddb1a18c.png)

Je vois pourtant bien les infos depuis la rest api : /admin/rest/automate-execution?_=1594966063785.

**Comment by Ousret** [comment]
Re:

Un correctif pour votre remarque est disponible sous la version 1.0.15
Dites-moi si le problème persiste encore chez vous.

Merci

**Comment by Ousret** [comment]
Re:

Avez-vous pu résoudre le pb ? Vais-je clore le ticket ?
