### ISSUE TITLE
Erreur lors de la création du container - Docker creation error

### ISSUE THREAD

**Issue by SadarSSI** [Ousret/hermes#47]
Installed /usr/local/lib/python3.8/site-packages/Flask_Babel-2.0.0-py3.8.egg
error: Flask-Babel 2.0.0 is installed but flask_babel==1.0.* is required by {'hermes'}
Removing intermediate container e3ea342b71f2
The command '/bin/sh -c python setup.py install' returned a non-zero code: 1

J'ai modifié le fichier setup.py pour accepter la version de Flask_Babel... Par contre je n'ai aucune idée de l'impact de cela sur Hermes.

Une idée ?

**Comment by Ousret** [comment]
Bonjour @SadarSSI 

En effet, j'ai raté ça. Je viens de rafraichir le Dockerfile pour combler ce problème.
Après test, l'effet semble inexistant, la nouvelle version majeure ne semble pas être trop différente ou n'introduit aucun BC break.

à surveiller.

**Comment by dutch2005** [comment]
just tested, can confirm I can make a docker image now.
