### ISSUE TITLE
HERMES : Problème avec le contenu de la variable Corps sur les actions Core/update, Core/create

### ISSUE THREAD

**Issue by Dsniss** [Ousret/hermes#5]
Bonjour

J'utilise Hermes afin de traiter des mails et le cas échéant créer ou mettre à jour un ticket dans l'outil ITSM iTop.
Lors de la création ou MAJ du ticket iTop je constate que :
- le champ iTop "public_log" alimenté avec la valeur {{corps|escapeQuote}}
ou 
- le champ iTop "description" alimenté avec la valeur {{corps|escapeQuote}}
est systématiquement alimenté avec un contenu en double (cf. copie écran)
![Capture](https://user-images.githubusercontent.com/59965868/72810583-2c892800-3c5e-11ea-8d4f-d6d353aa2a90.JPG)

Alors que dans Hermes le champ corps perçu par le moteur ne fait pas apparaître de doublons !!

Ce constat fait suite à la dernière évolution concernant l'auto détection selon que le message soit formaté en HTML ou en texte brut.

Merci et bonne journée
@Dsniss

**Comment by Ousret** [comment]
Bonjour @Dsniss ,

Je verrai si au niveau des filtres il y a un problème.

**Comment by Dsniss** [comment]
Bonjour @Ousret 

Ok super et merci.
Effectivement le bug n'est pas critique .. 
c'est juste que le contenu du mail (partie corps) apparaît en double dans l'historique de nos échanges mémorisés dans l'outil ITOP.
Si tu as de la visibilité sur une date de correction je suis preneur

Excellente journée

**Comment by Ousret** [comment]
Un correctif est disponible, j'espère qu'il aidera à résoudre ce problème. 

Bonne journée

**Comment by Ousret** [comment]
Je considère le problème comme étant résolu.
