### ISSUE TITLE
HERMES : Contenu /chargement des variables globales

### ISSUE THREAD

**Issue by Dsniss** [Ousret/hermes#6]
Bonjour @Ousret 

Nous rencontrons un cas de figure bloquant sur notre PROD. A savoir que lors de l'exécution d'un automate je constate que le contenu de variables globales diffère de celui défini dans "Mes variables globales" ce qui génère des erreurs (ci-dessous un exemple)

### **Contenu de la variable globale nommée "Configuration ITOP" :**

```json
{
  "itop": {
    "url": "https://serveur",
    "utilisateur": "user",
    "mot_de_passe": "pwd",
  }
}
```

### **Contenu des actions dans l'automate en erreur**
![image](https://user-images.githubusercontent.com/59965868/73283901-0e8a6d00-41f4-11ea-9590-f090be13f05a.png)
![image](https://user-images.githubusercontent.com/59965868/73283936-18ac6b80-41f4-11ea-8894-f36a9fb2e5c2.png)
![image](https://user-images.githubusercontent.com/59965868/73283972-29f57800-41f4-11ea-8280-aa72cd78ee28.png)

### **Constat du chargement des variables lors de l'exécution de l'automate**
```
2020-01-28 16:56:39.301 | INFO  | hermes_ui.moteur.processus:thread:32 - Chargement des variables globales passées en base de données
2020-01-28 16:56:39.305 | INFO     | hermes_ui.moteur.processus:thread:36 - Chargement de la configuration <'Configuration ITOP'::JSON>
```

### **Constat d'une erreur** 
![image](https://user-images.githubusercontent.com/59965868/73283226-14338300-41f3-11ea-872b-a9936264b8d5.png)

### **Vérif. LOG et constat contenu différent de ce qui est défini**
![image](https://user-images.githubusercontent.com/59965868/73283713-cff4b280-41f3-11ea-9c5c-5cfd419de3c6.png)

Est il possible de savoir quelle(s) action(s) effectuer pour résoudre ce problème ?

Merci ton aide @Ousret 

@Dsniss

**Comment by Ousret** [comment]
Bonjour,

Voulez-vous vérifier si une variable est en conflit, par ex. une variable s'appellant itop dans votre automate ou règles ?
C'est probablement un problème de votre côté. Il est possible d'envisager une évolution pour lever une erreur lorsqu'il existe en double une variable du même nom. La seconde écrasant la première.

Merci

**Comment by Ousret** [comment]
@Dsniss

**Comment by Dsniss** [comment]
Bonjour @Ousret

 

J’ai essayé de voir si j’avais une variable en conflit (exemple : itop) mais impossible de savoir laquelle si toutefois il y en a une.

La chose dont je suis sûr c’est que pour l’automate en erreur (car ce n’est pas le cas avec tous les automates) il ne me semble pas y avoir deux fois la même variable.

Il y aurait-il un mode debug plus bavard pour voir ce qu’il se passe car j’ai reproduit l’erreur sur notre plateforme de test ?

 

Merci @Ousret (Ahmed) J

 

Dsniss

 

De : TAHRI Ahmed R. [mailto:notifications@github.com] 
Envoyé : vendredi 31 janvier 2020 10:15
À : Ousret/hermes
Cc : Dsniss; Mention
Objet : Re: [Ousret/hermes] HERMES : Contenu /chargement des variables globales (#6)

 

@Dsniss <https://github.com/Dsniss>

**Comment by Dsniss** [comment]
Bonjour @Ousret

Je viens de vérifier et ne constate pas d'éventuel conflit.
Après plusieurs essais je remarque qu'avec le même automate et deux mails de même type (Mais avec un contenu différent) le résultat diffère. Pour l'un tout est ok mais pas pour l'autre !!!!!!

Je pense qu'Hermes se trouve face à un caractère, code, ou chaîne de caractères qui lui pose problème. Pour info avec le mail en erreur il y a une image d'intégrée ..

![image](https://user-images.githubusercontent.com/59965868/73766049-c16b4580-4775-11ea-9462-21bb573f3340.png)

![image](https://user-images.githubusercontent.com/59965868/73767429-bc0efa80-4777-11ea-866f-3c2953209c9f.png)

Puis-je t'envoyer le mail qui pose problème .. ? vers une bal plus sécure.

Merci et bonne journée

@Dsniss

**Comment by Ousret** [comment]
Pour une analyse approfondie, j'ai besoin de : 
  - Import des automates au format JSON
  - Un import de message *.msg ou *.eml déclanchant le problème 
  - La liste des variables globales enregistrées

Si, bien sûr, le problème est toujours d'actualité, ********

**Comment by Ousret** [comment]
Un correctif va être publié. cf. PR #7 (version 1.0.3)
Si le problème est résolu, merci de fermer cette issue.

```bash
./upgrade.sh
```

**Comment by Dsniss** [comment]
Bonjour @Ousret 

Après avoir installé la dernière release je n'ai effectivement plus d'erreur.
Cependant l'image intégrée dans le mail d'origine (certainement à l'origine de l'erreur) n'est pas prise en compte ... donc absente !! Ce constat est il normal ??

Merci et très bonne journée @Ousret 

@Dsniss

**Comment by Ousret** [comment]
Bonjour @Dsniss 

Bonne nouvelle. Aucune idée pour l'image, mais tant que ce n'est pas bloquant, laissons.
Je ferme le ticket par la même occasion.

Bonne journée.

**Comment by Dsniss** [comment]
Bonjour Ahmed,

Je comprends que le problème n'est plus bloquant.
Mais en l'état nous perdons le contenu complet du mail .... et l'image que j'évoque est justement une copie écran d'une erreur envoyée à l'utilisateur.
Du coup sans cette copie écran (image) impossible de connaître avec précision le contenu du mail reçu.

Merci pour ta compréhension

@Dsniss


----- Mail original -----
De: "TAHRI Ahmed R." <notifications@github.com>
À: "Ousret/hermes" <hermes@noreply.github.com>
Cc: "Dsniss" <denis.guilloteau1@libertysurf.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 27 Février 2020 13:46:03
Objet: Re: [Ousret/hermes] HERMES : Contenu /chargement des variables globales (#6)



Bonjour @Dsniss 

Bonne nouvelle. Aucune idée pour l'image, mais tant que ce n'est pas bloquant, laissons. 
Je ferme le ticket par la même occasion. 

Bonne journée.

**Comment by Ousret** [comment]
Re :

D’accord. Je ne comprends pas tout. Essaye de créer un nouveau ticket en expliquant le problème avec autant de détails que possible.

Est-ce le problème arrive partout où sur un cas précis ?

Merci.

**Comment by Dsniss** [comment]
Ahmed,

Si tu reprends le mail que je t'avais envoyé en exemple (le revoici en PJ) c'est plus facile de comprendre.

En fait, il arrive que notre infogérant nous envoient des mails (demandes) dans lesquels il ajoute des copies écrans (images).
L'objectif est donc qu'ITOP puisse créer automatiquement un ticket à la réception de ce mail et donc de récupérer tout son contenu

Avec la correction que tu as apportée, la création a bien lieu ... jusqu'ici c'est parfait.
Mais dans le ticket ITOP il manque dans la partie description la copie écran envoyée par l'infogérant (cf. PJ DescriptionTicketItop.JPG).

Le problème arrive uniquement lorsqu'il y a une copie écran (que j'ai appelée image dans nos précédents échanges).

Pour toi c'est plus clair ?

Merci pour ton aide et très bonne fin de semaine

Denis


----- Mail original -----
De: "TAHRI Ahmed R." <notifications@github.com>
À: "Ousret/hermes" <hermes@noreply.github.com>
Cc: "Dsniss" <denis.guilloteau1@libertysurf.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Jeudi 27 Février 2020 14:08:37
Objet: Re: [Ousret/hermes] HERMES : Contenu /chargement des variables globales (#6)



Re : 

D’accord. Je ne comprends pas tout. Essaye de créer un nouveau ticket en expliquant le problème avec autant de détails que possible. 

Est-ce le problème arrive partout où sur un cas précis ? 

Merci.
