### ISSUE TITLE
HERMES : Copie écran dans le corps d'un mail non pris en compte

### ISSUE THREAD

**Issue by Dsniss** [Ousret/hermes#8]
Bonjour @Ousret

Comme évoqué dans un de nos échanges j'ouvre un nouveau ticket vis à vis d'un constat déjà évoqué.

Lorsque nous recevons un émail dont le corps du message intègre une copie écran et que notre souhait est d'utiliser l'action core/create pour créer un ticket dans ITOP, on constate qu'HERMES n’intègre pas la copie écran présente dans le corps du message d'origine

Ci-dessous un exemple de contenu de mail avec une partie texte / html et dans l'encadré en rouge la copie écran évoquée.

![ExempleContenuDuMail](https://user-images.githubusercontent.com/59965868/75867817-73467200-5e07-11ea-9cee-41165d6424f5.jpg)

Ci-dessous le résultat de ce qui a été récupéré dans le corps du message par HERMES avec le constat que la copie écran n'est pas prise en compte

![PartieRecupereeParHermes](https://user-images.githubusercontent.com/59965868/75868942-21065080-5e09-11ea-90d2-56050fcbd04d.jpg)

Merci pour ton aide

Bonne journée

@Dsniss

**Comment by Ousret** [comment]
Bonjour @Dsniss ,

Après constatation, impossible de répliquer le bug. Je conjecture par mes tests qu'iTop refuse de prendre une balise html img ayant une représentation base64. De mon côté, avec la dernière version je récupère bel et bien les captures.

Voilà un extrait du corps HTML. 

```html
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABSAAAACJCAIAAACzXAHHAAAgAElEQVR4n............./>
```

Je te recommande de regarder ce qu'il y a en base de données. Peut-être solliciter Combodo pour vérifier si le comportement est normal.

Bien à toi.

**Comment by Dsniss** [comment]
Bonjour @Ousret 

Après plusieurs tests suite à tes modifs je constate qu'ITOP ne prend pas en compte la copie écran. 
Comme proposé, j'ai regardé en base de données. Au niveau de la balise html img j'ai uniquement ceci

![Enbase](https://user-images.githubusercontent.com/59965868/76508781-3c97d980-644f-11ea-92ca-f6f0a9f43e19.JPG)

j'ai donc fait un autre test celui de passer par l'incomingmail d'ITOP pour voir comment il allait prendre en compte le mail d'origine et là j'ai exactement le même problème à savoir que la copie écran n'est pas prise en compte / trouvée (cf. trace ci-dessous)

![image](https://user-images.githubusercontent.com/59965868/76509382-3fdf9500-6450-11ea-8922-2680dabc8828.png)

J'en déduis donc et comme tu l'avais évoqué que l'anomalie vient d'ITOP.

Merci @Ousret  et très bonne journée

@Dsniss :)
